### ISSUE TITLE
Unable to make POST requests with a POST body to Azure Functions API

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-fetch#142]
Test case to follow

**Comment by tripodsan** [comment]
problem still persists - or is even worse with the new version  2.1.6

```
Unable to deploy Lambda function: socket hang up Error [TimeoutError]: socket hang up
    at connResetException (internal/errors.js:607:14)
    at TLSSocket.socketOnEnd (_http_client.js:493:23)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  '$metadata': { attempts: 3, totalRetryDelay: 327 }
}
error: AmazonWebServices - socket hang up
```

also see CI in https://app.circleci.com/pipelines/github/adobe/helix-deploy?branch=renovate-adobe-fixes

**Comment by tripodsan** [comment]
nevermind....it seems to be a network error on my side / AWS side....
