### ISSUE TITLE
node exit with Error [ERR_HTTP2_SESSION_ERROR]

### ISSUE THREAD

**Issue by ranbochen** [adobe/helix-fetch#237]
**Description**
process crashed with error when fetch in try-catch context
the exception was caught, but nodejs still exit.

**Version:**
"@adobe/helix-fetch": "^3.0.0"
nodejs v16.13.0

Crash log:
[2021/12/31 20:26:23][error] error: FetchError - Session closed with error code 1
[2021/12/31 20:26:23][info] retry after 10s 
Error [ERR_HTTP2_SESSION_ERROR]: Session closed with error code 1
    at new NodeError (node:internal/errors:371:5)
    at Http2Session.onGoawayData (node:internal/http2/core:679:21) {
  code: 'ERR_HTTP2_SESSION_ERROR'
}

**Comment by stefan-guggisberg** [comment]
Is this reproducible? If so please provide  self-contained example code which demonstrates the issue.

**Comment by ranbochen** [comment]
It rarely happens.
I've only see it twice in the past month.

**Comment by tripodsan** [comment]
@ranbochen AFAIU, node doesn't crash (as in segfault / process.exit) but rather your code throws a unhandled exception.
`fetch` is allowed to throw error for different reasons, eg network down, host unreachable, dns error, etc. so those should probably be anticipated by your code and the request should be retried.

**Comment by ranbochen** [comment]
> @ranbochen AFAIU, node doesn't crash (as in segfault / process.exit) but rather your code throws a unhandled exception. `fetch` is allowed to throw errors for different reasons, eg network down, host unreachable, dns error, etc. so those should probably be anticipated by your code and the request should be retried.
> 
> you might also start node with `--trace-uncaught` to _show stack traces for the `throw` behind uncaught exceptions_.

I mean app crashed.
all my calls to fetch is in try-catch context,  
and  log shows error has been catched, but app still crashed.
that's odd

**Comment by tripodsan** [comment]
> all my calls to fetch is in try-catch context,

and you `await` the calls to `fetch` ?

**Comment by ranbochen** [comment]
sure thing~

the log says
there are two error throw out.

first: Http2 throw "NodeError", helix-fetch catch it and translate to "FetchError" , then throw to app.
my app catch "FetchError" and print it out.

then the second http2 "NodeError" happens, no one catch it, so app crashed.

**Comment by stefan-guggisberg** [comment]
see https://github.com/adobe/helix-fetch/issues/238#issuecomment-1005771491

**Comment by stefan-guggisberg** [comment]
Note that as of Node v16 unhandled promise rejections trigger `process.exit(1)` rather than just printing a warning on the console.

You can prevent the process termination by a adding a global `unhandledRejection` handler, e.g.:

```javascript
process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at:', promise, 'reason:', reason);
});
```

**Comment by ranbochen** [comment]
i think it's a nodejs issues, it may throw error twice in http2 module~
the first throw can be handled in try-catch, but the second ... nothing we can do in our code. 
add process.uncaughtException handler will prevent app crash
you can close the issue report.

```
[2022/1/9 19:57:16][info] 10 秒后重试
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
    at new NodeError (node:internal/errors:371:5)
    at ClientHttp2Stream._destroy (node:internal/http2/core:2313:13)
    at _destroy (node:internal/streams/destroy:102:25)
    at ClientHttp2Stream.destroy (node:internal/streams/destroy:64:5)
    at Http2Stream.onStreamClose (node:internal/http2/core:545:12)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}


[2022/1/10 22:53:52][debug] Starting work 
[2022/1/10 22:54:24][error] error: AbortError - The operation was aborted.
[2022/1/10 22:54:24][info] 10 秒后重试
node:events:368
      throw er; // Unhandled 'error' event
      ^

RequestAbortedError
    at EventEmitter.onAbortSignal (D:\proj\proj\node_modules\@adobe\helix-fetch\src\core\h2.js:235:14)
    at EventEmitter.emit (node:events:390:28)
    at AbortSignal.dispatchEvent (D:\proj\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:67:41)
    at AbortSignal.fire (D:\proj\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:72:10)
    at AbortController.abort (D:\proj\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:137:39)
    at Timeout._onTimeout (D:\proj\proj\dist\utils\fetch.js:36:49)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)


[2022/1/12 17:05:23][error] error: FetchError - The pending stream has been canceled (caused by: connect ETIMEDOUT 127.99.2.86:443)
[2022/1/12 17:05:23][info] 15 秒后重试
[2022/1/12 17:05:23][error] *******************************************************************
[2022/1/12 17:05:23][error] uncaughtException: Error
Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: connect ETIMEDOUT 127.99.2.86:443)
    at new NodeError (node:internal/errors:371:5)
    at closeSession (node:internal/http2/core:1133:20)
    at ClientHttp2Session.destroy (node:internal/http2/core:1512:5)
    at TLSSocket.socketOnError (node:internal/http2/core:2962:13)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  cause: Error: connect ETIMEDOUT 127.99.2.86:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '127.99.2.86',
    port: 443
  },
  code: 'ERR_HTTP2_STREAM_CANCEL'
}
[2022/1/12 17:05:23][error] *******************************************************************
```

**Comment by stefan-guggisberg** [comment]
@ranbochen Thanks for the update. I am closing this issue.
