### ISSUE TITLE
error fetching content via `post` (lowercase)

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#24]
**Description**
```
async function testFetch() {
  const context = fetchAPI.context({
    // httpProtocol: 'http1',
    // httpsProtocols: ['http1'],
  });
  try {
    const resp = await context.fetch('https://httpbin.org/post', {
      method: 'post',
      headers: {
        accept: 'application/json',
      }
    });
    console.log(resp.status);
    const text = await resp.text();
    return {
      statusCode: 200,
      body: text,
    };
  } finally {
    await context.disconnectAll();
  }
}
```

produces:

```
Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_PROTOCOL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2095:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:37:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2111:12)
    at Http2Stream.onStreamClose [as onstreamclose] (internal/http2/core.js:479:26)
```

**Additional context**
after forcing http1, it works.

**Comment by tripodsan** [comment]
same when using `https://www.nghttp2.org/httpbin/post`.

I found the problem: `method` needs to be all UPPERCASE.
